version: '3.8'

services:
  app:
    image: mrmlb/hello-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:latest
    platform: linux/arm64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000

networks:
  default:
    external:
      name: my-network
