version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    networks:
      - hello_network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: user
      DB_USERNAME: postgres
      DB_PASSWORD: 0000
    ports:
      - "8080:8080"
    networks:
      - hello_network

networks:
  hello_network:

volumes:
  db_data:
